# test --> build --> deploy

name: main Pipeline
on:
    push:
        branches:
            - main
    
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run tests
              run: npm run test
        
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build project
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifacts@v3
              with: 
                name: dist-files
                path: |
                  dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: deploy project
              run: echo "deploying.." 
            


         
