# test --> build --> deploy

name: main Pipeline
on:
    push:
        branches:
            - main
    
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run tests
              run: npm run test
        
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          script-file: ${{ steps.publish.outputs.js-file }}
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build project
              run: npm run build
            - name: publish js filename
              id: publish
              run: find dist/assets/*.js -type f --execdir echo "js-file={}" >> $GITHUB_OUTPUT ';'
            - name: upload artifacts
              uses: actions/upload-artifact@v7
              with: 
                name: dist-files
                path: |
                  dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: get build artifacts
              uses: actions/download-artifact@v8
              with:
                name: dist-files  
                
            - name: deploy project
              run: echo "deploying.." 
            


         
