name: firstWorkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
      - run: echo "Hello World !!"

      - name: Sendoff
      - run: echo "Have a good rest of the day!!"
