name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello World !!"
      - name: Print Goodbye
        run: echo "Have a good rest of the day!!"
